### PR TITLE
Updating installation tutorial

### PR DESCRIPTION
**Pull request by hogesonline**
Updating the windows commands for installation and connection to wifi. Also added some helpful debugging-type notes based on what happened in the actual workshop.

<My first non-hand-held contribution! : ) >

### CODE REVIEW

**Review by nickzoic — APPROVED** [review]
Brilliant, thanks!

PS: Did you know an easy way to get around the problem where running "esptool.py" opens your IDE?  I'm wondering if there's some way to run it as a shortcut instead.

**Comment by hogesonline** [comment]
Oops, I knew there was a thing I missed. I did:
`python -m esptool`

**Comment by hogesonline** [comment]
Actually that's important to do because I (and possibly others) have .py files defaulted to open in my text editor because teacher: It's much more common for me to need to read py files than to run them.

**Comment by nickzoic** [comment]
Yeah, totally.  I went and added a bug #5 for that so as not to forget.
Thanks for your contribution!  Was great to get some feedback on the
tutorial :-)
------Nick


On Sat, Jan 27, 2018, at 16:33, hogesonline wrote:
> Actually that's important to because I have .py files defaulted to
> open in my text editor because teacher: It's much more common for me
> to need to read py files than to run them.> — You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

--
Nick Moore <nick@zoic.org> 0409 656 267


Links:

  1. https://github.com/nickzoic/mpy-tut/pull/4#issuecomment-360961908

**Pull request merged**
